In [1]:
#QN-1
import numpy as np

# Random integers between 1 and 50, with size of array being 3 rows and 4 columns
arr_1 = np.random.randint(1, 51, size=(3, 4))
print(arr_1)


[[50  1 20  2]
 [ 4 18 20 29]
 [19  1 45 50]]


In [2]:
print("The mean =",np.mean(arr_1))                    # calculating mean

print("The median =",np.median(arr_1))                # calculating median

print("The Standard Deviation =",np.std(arr_1))       # calculating SD

print("The sum =",np.sum(arr_1))                      # calculating sum

print("Sum of each row:", np.sum(arr_1, axis=1))      # calculating sum of each row

print("The reshape matrix is :\n",arr_1.reshape(2,6))                             # Reshaping 3*4 matrix to 2*6


The mean = 21.583333333333332
The median = 19.5
The Standard Deviation = 17.75508534351653
The sum = 259
Sum of each row: [ 73  71 115]
The reshape matrix is :
 [[50  1 20  2  4 18]
 [20 29 19  1 45 50]]


In [5]:
import numpy as np

# Create two matrices of random values of size 3*3
arr_2 = np.random.randint(1, 10, size=(3, 3))
arr_3 = np.random.randint(1, 10, size=(3, 3))

# Print both matrix, addition, substraction, multiplication, dot product, transpose
print("Matrix A:\n", arr_2)
print("Matrix B:\n", arr_3)
print("\nMatrix Addition (A + B):\n", arr_2 + arr_3)
print("\nMatrix Subtraction (A - B):\n", arr_2 - arr_3)
print("\nElement-wise Multiplication (A * B):\n", arr_2 * arr_3)
print("\nDot Product (A . B):\n", np.dot(arr_2, arr_3))
print("\nTranspose of Matrix A:\n", np.transpose(arr_2))
print("\nTranspose of Matrix B:\n", np.transpose(arr_3))

# Determinant and Inverse of Matrix A
det_arr_2 = np.linalg.det(arr_2)
print("Determinant of Matrix A:", det_arr_2)
if not np.isclose(det_arr_2, 0):  # Check if determinant is not zero
    inv_arr_2 = np.linalg.inv(arr_2)
    print("Inverse of Matrix A:\n", inv_arr_2)
else:
    print("Determinant is 0, so inverse does not exist.")

# Determinant and Inverse of Matrix B
det_arr_3 = np.linalg.det(arr_3)
print("Determinant of Matrix B:", det_arr_3)
if not np.isclose(det_arr_3, 0):  # Check if determinant is not zero
    inv_arr_3 = np.linalg.inv(arr_3)
    print("Inverse of Matrix B:\n", inv_arr_3)
else:
    print("Determinant is 0, so inverse does not exist.")


Matrix A:
 [[8 5 9]
 [9 9 9]
 [5 7 2]]
Matrix B:
 [[2 4 8]
 [3 6 2]
 [9 9 3]]

Matrix Addition (A + B):
 [[10  9 17]
 [12 15 11]
 [14 16  5]]

Matrix Subtraction (A - B):
 [[ 6  1  1]
 [ 6  3  7]
 [-4 -2 -1]]

Element-wise Multiplication (A * B):
 [[16 20 72]
 [27 54 18]
 [45 63  6]]

Dot Product (A . B):
 [[112 143 101]
 [126 171 117]
 [ 49  80  60]]

Transpose of Matrix A:
 [[8 9 5]
 [5 9 7]
 [9 9 2]]

Transpose of Matrix B:
 [[2 3 9]
 [4 6 9]
 [8 2 3]]
Determinant of Matrix A: -62.99999999999999
Inverse of Matrix A:
 [[ 0.71428571 -0.84126984  0.57142857]
 [-0.42857143  0.46031746 -0.14285714]
 [-0.28571429  0.49206349 -0.42857143]]
Determinant of Matrix B: -180.0
Inverse of Matrix B:
 [[ 7.70988212e-19 -3.33333333e-01  2.22222222e-01]
 [-5.00000000e-02  3.66666667e-01 -1.11111111e-01]
 [ 1.50000000e-01 -1.00000000e-01 -1.85037171e-18]]
